Exit weather script if jq is not installed

diff --git a/.bin/weather b/.bin/weather
--- a/.bin/weather
+++ b/.bin/weather
@@ -52,6 +52,11 @@ weather_icon() {
   esac
 }
 
+if ! [ -x "$(command -v jq)" ]; then
+  echo "Error: jq is not installed." >&2
+  exit 1
+fi
+
 LOCATION=$(curl --silent http://ip-api.com/csv)
 CITY=$(echo "$LOCATION" | cut -d , -f 6)
 LAT=$(echo "$LOCATION" | cut -d , -f 8)
